sink("./output.txt", append = T)
 name<-("Comfort Ojedapo")
> email<-("osinugacomfort@gmail.com")
> slackusername<-("@comfort")
> biostack<-("epigenomics")
> twitter_handle<-("@osinugacomfort")
> hamming_distance<-("0")
cat(name,email,slackusername,biostack,twitter_handle,hamming_distance, sep =",")
sink()
